CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [FirstName] NVARCHAR(255) NOT NULL, 
    [LastName] NVARCHAR(255) NOT NULL, 
    [Email] NVARCHAR(255) Unique NOT NULL, 
    [PasswordHash] NVARCHAR(512) NOT NULL
)
